/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.*;
//import sun.audio.*;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

public class RPSDemoForm extends javax.swing.JFrame {

    /**
     * Creates new form RPSDemoForm
     */
    public RPSDemoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/normalFace.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "One Game", "5 Games", "Infinite" }));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NormalFace.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rock", "Paper", "Scissors" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Your Choice:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("YOU");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("COMPUTER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(374, 374, 374))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = jComboBox1.getSelectedIndex();
        switch(index){
            case 0:
                theFinalWinner = playOneGame();
                changeFaces(theFinalWinner);
                break;
            case 1:
                theFinalWinner = playFiveGames();
                changeFaces(theFinalWinner);
                break;
            case 2:
                theFinalWinner = playInfiniteGames();
                changeFaces(theFinalWinner);
                break;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        try{
            if(theFinalWinner.equals("YOU"))
                in = new FileInputStream(applauseFile);
            else if (theFinalWinner.equals("COMPUTER"))
                in = new FileInputStream(booFile);

            // create an audiostream from the inputstream
            audioStream = new AudioStream(in);
            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        }
        catch (Exception e)
        {
            System.out.println("Audio file couldn't play!");
        }
//    AudioPlayer.player.start(audioStream);

    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        AudioPlayer.player.stop(audioStream);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        try{
            if(theFinalWinner.equals("YOU"))
                in = new FileInputStream(booFile);
            else if (theFinalWinner.equals("COMPUTER"))
                in = new FileInputStream(applauseFile);
            audioStream = new AudioStream(in);
            // create an audiostream from the inputstream
            AudioPlayer.player.start(audioStream);
        }
        catch (Exception e)
        {
            System.out.println("Audio file couldn't play!");
        }
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        AudioPlayer.player.stop(audioStream);
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPSDemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPSDemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPSDemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPSDemoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPSDemoForm().setVisible(true);
            }
        });
    }


    private String playOneGame(){
	String theWinner;
        String myHand = jComboBox2.getSelectedItem().toString();
        int compIndex = ((int)(Math.random() * 100) % 3);

        theWinner = whoIsTheWinner(myHand, computerHand[compIndex]);
        return theWinner;
    }
    private String playFiveGames(){
	//enter your code here
        String theWinner = "TIE";
        String yourHand;
        String compHand;

        //example code below.  You have to implement your own code here
        for(int index = 0; index<5; ++index)
        {
            //Hint.
            //Get your hand the same way as "playOneGame
            //Get computer's hand the samy way as "playOneGame"
            //call "whoIsTheWinner" five times.
            //return the winner.
        }
        return theWinner;
    }
    private String playInfiniteGames(){
    	String myHand, compHand,theWinner="TIE";
        int response = JOptionPane.showConfirmDialog(null, "Keep Playing?", "Computer is asking you...", JOptionPane.YES_NO_OPTION);
        while(response == JOptionPane.YES_OPTION)
        {
            //Hint.
            //Get your hand the same way as "playOneGame
            //Get computer's hand the samy way as "playOneGame"
            //call "whoIsTheWinner" five times.
            //return the winner.
        }
        return theWinner;
    }

    private String whoIsTheWinner(String myHand, String compHand){
        String theWinner="TIE";
        switch (myHand)
        {
            case "Rock":
                if(compHand.equals("Paper"))
                    theWinner="COMPUTER";
                else if (compHand.equals("Scissors"))
                    theWinner="YOU";
            break;
            case "Paper":
                if(compHand.equals("Rock"))
                    theWinner="YOU";
                else if (compHand.equals("Scissors"))
                    theWinner="COMPUTER";
            break;
            case "Scissors":
                if(compHand.equals("Rock"))
                    theWinner="COMPUTER";
                else if (compHand.equals("Paper"))
                    theWinner="YOU";
            break;
        }
        return theWinner;
   }

    private void changeFaces(String fWinner){
        switch (fWinner){
            case "YOU":
            jLabel1.setIcon(happyImg);
            jLabel2.setIcon(sadImg);
            break;
            case "COMPUTER":
            jLabel1.setIcon(sadImg);
            jLabel2.setIcon(happyImg);
            break;
            case "TIE":
            jLabel1.setIcon(normalImg);
            jLabel2.setIcon(normalImg);
        }
    }


/**************************************************************************************
 * bellow are class level variables
 *************************************************************************************/
    String[] computerHand = {"Rock","Paper","Scissors"};
    String theFinalWinner = "";

    //Image files
    ImageIcon sadImg = new ImageIcon(".\\src\\sadFace.png");
    ImageIcon happyImg = new ImageIcon(".\\src\\happyFace.png");
    ImageIcon normalImg = new ImageIcon(".\\src\\normalFace.jpg");

    //Audio files
    String booFile = ".\\src\\boo.wav";
    String applauseFile = ".\\src\\applause.wav";
    AudioStream audioStream;
    InputStream in;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
